import type { Property } from '@/types/properties'

export const mockProperty: Property = {
  id: '123e4567-e89b-12d3-a456-426614174000',
  agency_id: 'agency-123',
  producer_id: 'user-123',
  title: 'Casa en Polanco',
  description: 'Hermosa casa con jardín amplio y acabados de lujo',
  property_type: 'house',
  operation_type: 'sale',
  status: 'active',
  address: {
    street: 'Masaryk 123',
    neighborhood: 'Polanco',
    city: 'Ciudad de México',
    state: 'CDMX',
    postal_code: '11560',
    country: 'México',
  },
  coordinates: { lat: 19.4326, lng: -99.1332 },
  show_exact_location: true,
  bedrooms: 3,
  bathrooms: 2,
  half_bathrooms: 1,
  parking_spaces: 2,
  construction_m2: 180,
  land_m2: 200,
  total_m2: 200,
  floors: 2,
  year_built: 2020,
  sale_price: 5000000,
  rent_price: undefined,
  currency: 'MXN',
  maintenance_fee: 3000,
  amenities: ['pool', 'garden', 'gym'],
  features: {},
  shared_in_mls: true,
  commission_shared: true,
  commission_percentage: 3,
  is_exclusive: false,
  health_score: 85,
  photos: [
    'https://example.com/photo1.jpg',
    'https://example.com/photo2.jpg',
  ],
  videos: [],
  views_count: 42,
  favorites_count: 5,
  inquiries_count: 3,
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-15T00:00:00Z',
}

export const mockRentalProperty: Property = {
  ...mockProperty,
  id: '223e4567-e89b-12d3-a456-426614174001',
  title: 'Departamento en Roma Norte',
  property_type: 'apartment',
  operation_type: 'rent',
  sale_price: undefined,
  rent_price: 25000,
  bedrooms: 2,
  bathrooms: 1,
  construction_m2: 80,
  land_m2: undefined,
  health_score: 60,
  photos: [],
}

export const mockProperties: Property[] = [
  mockProperty,
  mockRentalProperty,
  {
    ...mockProperty,
    id: '323e4567-e89b-12d3-a456-426614174002',
    title: 'Terreno en Coyoacán',
    property_type: 'land',
    operation_type: 'sale',
    sale_price: 3000000,
    status: 'draft',
    bedrooms: undefined,
    bathrooms: undefined,
    health_score: 30,
  },
]
