// /src/app/api/cron/tasks/route.ts
import { NextRequest, NextResponse } from 'next/server'

export async function GET(request: NextRequest) {
    try {
        // Verify authorization
        const authHeader = request.headers.get('authorization')
        if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
        }

        const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'

        // Call both endpoints
        const [autoGenerate, checkOverdue] = await Promise.all([
            fetch(`${baseUrl}/api/tasks/auto-generate`, {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${process.env.CRON_SECRET}`
                }
            }),
            fetch(`${baseUrl}/api/tasks/check-overdue`, {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${process.env.CRON_SECRET}`
                }
            })
        ])

        const autoGenerateData = await autoGenerate.json()
        const checkOverdueData = await checkOverdue.json()

        return NextResponse.json({
            success: true,
            auto_generate: autoGenerateData,
            check_overdue: checkOverdueData
        })

    } catch (error: any) {
        console.error('Error in cron tasks:', error)
        return NextResponse.json(
            { error: error.message },
            { status: 500 }
        )
    }
}
